# Generated by Django 3.1.5 on 2021-03-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_auto_20210121_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceLabelForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faces.facelabel')),
            ],
        ),
        migrations.CreateModel(
            name='FaceImageForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(max_length=200, upload_to='')),
                ('face_image', models.ImageField(editable=False, max_length=250, upload_to='')),
                ('embedding', models.BinaryField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='faces.facelabelfortest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
